name: Release

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.24"

      - name: Build
        run: make build

      - name: Create Release
        run: |
          gh release delete latest --yes --cleanup-tag || true
          gh release create latest \
            --title "latest" \
            --notes "Latest build" \
            ./build/ecalc ./build/ecalc.exe ./build/ecalc32.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
